{{- $fullName := include "layer0_describo.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "layer0_describo.labels" . | indent 4 }}
  annotations:
{{ include "common.ingressAnnotations" . | indent 4 }}
spec:
  {{- with (include "common.tlsSecretName" .) }}
  tls:
    - hosts:
        - {{ $.Values.domain }}
      secretName: {{ . }}
  {{- end }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
