global:
  image:
    tag: v0.2.2
  namespace:
    name: rds
  describo:
    domain: test-describo.localdomain.test
  rds:
    domain: test-rds.localdomain.test
  # Domains you want to use as input,
  # this enables to use multiple owncloud instances with a single sciebo RDS
  domains:
    #- name: test-nextcloud.localdomain.test # name needs to be exact the same as the second part after last @ in the cloudId
      # When deploying The EFSS locally in the k8s environment, we need to acces it both from within
      # the environment, from other pods, and from the outside, thus Address and INTERNAL_ADDRESS
      #INTERNAL_ADDRESS: http://nextcloud:8080
      #ADDRESS: https://test-nextcloud.localdomain.test
      #OAUTH_CLIENT_ID: tx5n6WHhXmHnP2GPKiNEHEmq3c9cM3pPHNyowISEAstDvtMkAOSuL5JfZ6hAXQ8G
      #OAUTH_CLIENT_SECRET: CnYhJyYj0OEq3CWgCYu9kpsnasB3gy6O4FQ0tE4n3qtUNF0fi4nxqxUmWJW9qpty
      #SUPPORT_EMAIL: mail@localdomain.test
      #MANUAL_URL: usermanual.localdomain.test
    #- name: test-owncloud.localdomain.test # name needs to be exact the same as the second part after last @ in the cloudId
      # When deploying The EFSS locally in the k8s environment, we need to acces it both from within
      # the environment, from other pods, and from the outside, thus Address and INTERNAL_ADDRESS
      #INTERNAL_ADDRESS: http://owncloud:8080
      #ADDRESS: https://test-owncloud.localdomain.test
      #OAUTH_CLIENT_ID: cDNKn1PGQ7nwLaJ2QxVvHIt30Z9EteErMayjGWpfywpnK027BmJIWu4RsQwXu21I
      #OAUTH_CLIENT_SECRET: 3tChKfr4rOEIPmtFbJs3gOhR07VdxJM997WVmZoc41EsWNjlzsPICQ67hnUFu1bR
      #SUPPORT_EMAIL: mail@localdomain.test
      #MANUAL_URL: usermanual.localdomain.test
loglevel: DEBUG
# If you set this to "False", SSL will not be verified in all https requests. Default: "True"
verify_ssl: False
layer0-describo:
  enabled: true
  environment:
    ADMIN_PASSWORD: your-admin-password
    LOG_LEVEL: "debug"
  postgresql:
    # starts its own postgresql database.
    postgresqlDatabase: describo
    postgresqlUsername: admin
    postgresqlPassword: admin
  domain: test-describo.localdomain.test
layer0-helper-describo-token-updater:
  enabled: true
  environment:
    DESCRIBO_API_ENDPOINT: http://layer0-describo/api/session/application
layer0-web:
  enabled: true
  environment:
    # the password, which will be used to encrypt all user data
    SECRET_KEY: 1234
    EMBED_MODE: true
layer1-port-owncloud:
  # ownCloud will be configured through global.domains, because this way you need to configure it only once
  enabled: true
layer1-port-zenodo:
  enabled: true
  environment:
    # needs to be adjusted to correct values
    ADDRESS: https://sandbox.zenodo.org
    OAUTH_CLIENT_ID: Bl6JYLJ08C8TF7ISObcf6122XztSuutmqLz5dYIw
    OAUTH_CLIENT_SECRET: JKTjeoWbdMbYfiNS8yBJEG5422otVvLTY8P22UHOGb74MWreQgQBlokqf1Wq
layer1-port-openscienceframework:
  enabled: true
  environment:
    ADDRESS: https://accounts.test.osf.io
    API_ADDRESS: https://api.test.osf.io/v2
    # needs to be adjusted to correct values
    OAUTH_CLIENT_ID: e4e77fab2a4f4acd941795370c6c5553
    OAUTH_CLIENT_SECRET: UNiavv9Uub3uvM69LLZda1C6miBYyn5NGK6OGGYO
layer2-port-service:
  # fullnameOverride: layer2-port-service-test-rds-ed-integrations-com
  environment:
    TOKENSERVICE_STATE_SECRET: ABC
    IGNORE_PROJECTS: True # this ignores the pull algo for external projects
layer3-research-manager: {}
layer3-token-storage: {}
feature:
  jaeger: false
  nextcloud: true
  owncloud: true

nextcloud:
  fullnameOverride: nextcloud
  ingress:
    enabled: true
  nextcloud:
    host: test-nextcloud.localdomain.test
    username: admin
    password: password
    extraEnv:
      - name: OVERWRITEHOST
        value: test-nextcloud.localdomain.test
      - name: OVERWRITEPROTOCOL
        value: https
      - name: NEXTCLOUD_TRUSTED_DOMAINS
        value: "test-nextcloud.localdomain.test nextcloud"

owncloud:
  fullnameOverride: owncloud
  externalDomain: test-owncloud.localdomain.test
  ingress:
    enabled: true
  insecure:
    # disables ssl certificate checking for connections to the openID connect identity provider.
    # Not recommended for production setups, but we don't have valid certificates in minikube
    oidcIdpInsecure: true
    # disables ssl certificate checking for connections to the oCIS http apis.
    # Not recommended for production setups, but we don't have valid certificates in minikube
    ocisHttpApiInsecure: true
  owncloud:
    domain: test-owncloud.localdomain.test
    adminUsername: admin
    adminPassword: password
    overwriteHost: test-owncloud.localdomain.test
    overwriteProtocol: https
    trustedDomains:
      - test-owncloud.localdomain.test
      - owncloud
