.use_case_exporter:
  variables:
    FOLDER: RDS/circle2_use_cases/exporter

.tests_use_case_exporter:
  extends:
    - .tests
    - .use_case_exporter

test:use_case_exporter3.8:
  image:  ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.8
  extends: .tests_use_case_exporter

build:use_case_exporter:
  needs:
    - test:use_case_exporter3.8
  extends:
    - .builds
    - .use_case_exporter

  only:
    changes:
      - RDS/circle2_use_cases/exporter/*
      - RDS/circle2_use_cases/exporter/**/*

doc:use_case_exporter:
  needs:
    - build:use_case_exporter
  image:  ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.8
  extends:
    - .documentation
    - .use_case_exporter
