.official_doc:
  variables:
    FOLDER: RDS/layer0_ingress/official_doc

build:official_doc:
  needs:
    - pages
  stage: pages
  cache:
    paths:
      - public
  extends:
    - .builds
    - .official_doc

  before_script:
    - cp public $FOLDER/public
