.central_service_research_manager:
  variables:
    FOLDER: RDS/circle3_central_services/research_manager

.tests_central_service_research_manager:
  extends:
    - .tests
    - .central_service_research_manager

test:central_service_research_manager3.8:
  image:  ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.8
  extends: .tests_central_service_research_manager

build:central_service_research_manager:
  needs:
    - test:central_service_research_manager3.8
  extends:
    - .builds
    - .central_service_research_manager

  only:
    changes:
      - RDS/circle3_central_services/research_manager/*
      - RDS/circle3_central_services/research_manager/**/*

doc:central_service_research_manager:
  needs:
    - build:central_service_research_manager
  image:  ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.8
  extends:
    - .documentation
    - .central_service_research_manager
