charts:
  stage: deploy
  image: zivgitlab.wwu.io/ulb/devops/skaffold:main
  variables:
    HELM_BRANCH: develop
  rules:
  - if: $CI_COMMIT_TAG
    variables:
      HELM_BRANCH: stable
  only:
    - release
  script:
    - mkdir -p ./pkgs
    - helm plugin install https://github.com/chartmuseum/helm-push.git
    - helm repo add --username gitlab-ci-token --password ${CI_JOB_TOKEN} ${CI_PROJECT_NAME} ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/${HELM_BRANCH}
    - for i in charts/*/;do helm package --destination ./pkgs "$i" ;done
    - for i in pkgs/*;do helm cm-push --force "pkgs/$i" ${CI_PROJECT_NAME} ;done

deploy:
  extends: .deploy
  image: zivgitlab.wwu.io/ulb/devops/skaffold:main
  script:
    - mkdir -p ~/.config/sops/age
    - cat "$AGE_KEYS" | base64 -d - > ~/.config/sops/age/keys.txt
    - mkdir -p ~/.kube
    - cat "$KUBE_CONFIG" | base64 -d - > ~/.kube/config
    - export KUBECONFIG=~/.kube/config
    - helm secrets upgrade -i sciebo-rds charts/all --values $HELM_DEPLOY_VALUES
