.port_openscienceframework:
  variables:
    OPENSCIENCEFRAMEWORK_API_KEY: $GITLAB_OPENSCIENCEFRAMEWORK_API_KEY
    FOLDER: RDS/layer1_adapters_and_ports/port_openscienceframework

.tests_port_openscienceframework:
  extends:
    - .tests
    - .port_openscienceframework

test:port_openscienceframework:
  extends: .tests_port_openscienceframework

build:port_openscienceframework:
  needs:
    - test:port_openscienceframework
  extends:
    - .builds
    - .port_openscienceframework

doc:port_openscienceframework:
  needs:
    - build:port_openscienceframework
  extends:
    - .documentation
    - .port_openscienceframework
