.use_case_metadata:
  variables:
    FOLDER: RDS/circle2_use_cases/metadata

.tests_use_case_metadata:
  extends:
    - .tests
    - .use_case_metadata

test:use_case_metadata3.8:
  image:  ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.8
  extends: .tests_use_case_metadata

build:use_case_metadata:
  needs:
    - test:use_case_metadata3.8
  extends:
    - .builds
    - .use_case_metadata

  only:
    changes:
      - RDS/circle2_use_cases/metadata/*
      - RDS/circle2_use_cases/metadata/**/*

doc:use_case_metadata:
  needs:
    - build:use_case_metadata
  image:  ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.8
  extends:
    - .documentation
    - .use_case_metadata
