.port_owncloud:
    variables:
        ZENODO_API_KEY: $GITLAB_ZENODO_API_KEY
        FOLDER: RDS/layer1_adapters_and_ports/port_owncloud

.tests_port_owncloud:
    extends:
        - .tests
        - .port_owncloud

test:port_owncloud:
    extends: .tests_port_owncloud

build:port_owncloud:
    needs:
        - test:port_owncloud
    extends:
        - .builds
        - .port_owncloud

doc:port_owncloud:
    needs:
        - build:port_owncloud
    extends:
        - .documentation
        - .port_owncloud
