baseurl = "https://www.research-data-services.org/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Sciebo RDS"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

enableGitInfo = true

[languages]


[languages.en]
    languageName = "English"
    weight = 1

[Params]
  subtitle = "Research data services"
  logo = "img/sciebo.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = false
  mainSections = []

#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Sciebo RDS Project Team"
  email = "sciebo-rds@uni-muenster.de"
#  facebook = "username"
#  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
#  gitlab = "username"
  github = "Sciebo-RDS/Sciebo-RDS"
#  twitter = "username"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  keybase = "username"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 10

[[menu.main]]
    name = "About"
    weight = 20
    url = "about"
    identifier = "about"

[[menu.main]]
    name = "Getting Started"
    weight = "25"
    
[[menu.main]]
    name = "Configuration"
    weight = "30"

[[menu.main]]
    name = "Development"
    identifier = "development"
    weight = "35"
    url = "/doc/contribute/contribute/"

[[menu.main]]
    name = "Reference"
    identifier = "ref"
    weight = "40"

# About

[[menu.about]]
    name = "Project"
    identifier = "rds"
    url = "/about"
    weight = "5"


[[menu.about]]
    name = "Contributors"
    identifier = "contributors"
    url = "/about/contributors"
    weight = "10"

[[menu.about]]
    name = "FAQ"
    identifier = "faq"
    url = "/about/faq"
    weight = "15"

# Development
[[menu.main]]
    name = "Monorepo"
    identifier = "monorepo"
    parent = "development"
    url = ""
    weight = "5"

[[menu.main]]
    name = "Contributing"
    identifier = "contributing"
    parent = "development"
    weight = "10"
    url = ""

[[menu.main]]
    name = "K8s Layers"
    identifier = "layers"
    parent = "development"
    weight = "15"
    url = ""

# Ref
[[menu.main]]
    name = "Environment"
    identifier = "env"
    parent = "ref"
    weight = "5"
    url = ""

[[menu.main]]
    name = "Glossary"
    identifier = "glossary"
    parent = "ref"
    weight = "10"
    url = ""

[[menu.main]]
    name = "Arc42"
    identifier = "arc42"
    parent = "ref"
    weight = "15"
    url = ""



#[[menu.main]]
#    name = "Contribute"
#    url = "/doc/contribute/contribute/"
#    weight = 25
    
#[[menu.main]]
#    name = "Doc"
#    url = "/doc/"
#    weight = 40

#[[menu.main]]
#    name = "Imprint"
#    url = "page/impr/"
#    weight = 50


# Documentation
#[[menu.doc]]
#    name = "Documentation"
#    identifier = "docs home"
#    pre = "<i class='fa fa-home'></i>"
#    url = "/doc/"
#    weight = -1050

#[[menu.doc]]
#    name = "Administration"
#    identifier = "installation"
#    pre = "<i class='fa fa-play'></i>"
#    weight = -900

#[[menu.doc]]
#    name = "User Manual"
#    identifier = "manual"
#    pre = "<i class='fa fa-book'></i>"
#    weight = -1000

#[[menu.doc]]
#    name = "Source Code"
#    identifier = "sourcecode"
#    pre = "<i class='fa fa-code'></i>"
#    url = "/doc/sourcecode/"
#    weight = 0

#[[menu.doc]]
#    name = "Contribute"
#    identifier = "contrib"
#    pre = "<i class='fa fa-code-fork'></i>"
#    url = "/doc/contribute/"
#    weight = -5
#    post = "border-top: 1px dotted #ccc;"

#[[menu.doc]]
#    name = "Architecture"
#    identifier = "architecture"
#    pre = "<i class='fa fa-university'></i>"
#    weight = -300
#    post = "border-top: 1px dotted #ccc;"


#[[menu.doc]]
#    name = "Infrastructure"
#    identifier = "infrastructure"
#    pre = "<i class='fa fa-industry'></i>"
#    weight = -290

#[[menu.doc]]
#    name = "Layer 0"
#    identifier = "ingress"
#    pre = "<i class='fa fa-plug'></i>"
#    weight = -290

#[[menu.doc]]
#    name = "Layer 1"
#    identifier = "adapter-port"
#    pre = "<i class='fa fa-map-o'></i>"
#    weight = -280

#[[menu.doc]]
#    name = "Layer 2"
#    identifier = "use-case"
#    pre = "<i class='fa fa-cogs'></i>"
#    weight = -270

#[[menu.doc]]
#    name = "Layer 3"
#    identifier = "core"
#    pre = "<i class='fa fa-archive'></i>"
#    weight = -260

#[[menu.doc]]
#    name = "Plugins"
#    identifier = "plugins"
#    pre = "<i class='fa fa-plug'></i>"
#    weight = -250

