.port_zenodo:
  variables:
    ZENODO_API_KEY: $GITLAB_ZENODO_API_KEY
    FOLDER: RDS/layer1_adapters_and_ports/port_zenodo

.tests_port_zenodo:
  extends:
    - .tests
    - .port_zenodo

test:port_zenodo:
  extends: .tests_port_zenodo
  allow_failure: true

build:port_zenodo:
  needs:
    - test:port_zenodo
  extends:
    - .builds
    - .port_zenodo

doc:port_zenodo:
  needs:
    - build:port_zenodo
  extends:
    - .documentation
    - .port_zenodo
