.official_doc:
  variables:
    FOLDER: RDS/layer0_ingress/official_doc

build:official_doc:
  needs:
    - pages
    - charts_pages
  stage: pages
  cache:
    paths:
      - public
  extends:
    - .builds
    - .official_doc

  before_script:
    - cp -r public $FOLDER/public

  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: '$CI_COMMIT_BRANCH == "release"'
    - if: "$CI_COMMIT_TAG"
      variables:
        DOC_FOLDER: .

deploy_doc:
  extends: .deploy
  image: harbor.uni-muenster.de/rds/testing
  needs: 
  - build:official_doc
  rules:
  - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  - if: '$CI_COMMIT_BRANCH == "release"'
  - if: "$CI_COMMIT_TAG"
  script:
    - mkdir -p ~/.kube
    - cat "$KUBE_CONFIG_DOC" | base64 -d - > ~/.kube/config
    - export KUBECONFIG=~/.kube/config
    - kubectl delete pod -l=app.kubernetes.io/instance=doc
